[package]
name = "handles"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = ["."]

[dependencies]
bevy = "0.19.1"
config = { git = "https://github.com/personal-rust-crates/config.git", branch = "master" }
encase = "=0.12.0"
serde = {version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde-big-array = "0.5.1"